// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnnuityCertainDue(arg1, arg2) {
  return window['go']['main']['App']['AnnuityCertainDue'](arg1, arg2);
}

export function AnnuityCertainImmediate(arg1, arg2) {
  return window['go']['main']['App']['AnnuityCertainImmediate'](arg1, arg2);
}

export function CTE(arg1, arg2) {
  return window['go']['main']['App']['CTE'](arg1, arg2);
}

export function CalcAnnuity(arg1) {
  return window['go']['main']['App']['CalcAnnuity'](arg1);
}

export function CalcReserve(arg1) {
  return window['go']['main']['App']['CalcReserve'](arg1);
}

export function CalculatePV(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculatePV'](arg1, arg2, arg3);
}

export function CalculatePVStar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CalculatePVStar'](arg1, arg2, arg3, arg4);
}

export function ComputeRiskMetrics(arg1) {
  return window['go']['main']['App']['ComputeRiskMetrics'](arg1);
}

export function ConvertRate(arg1) {
  return window['go']['main']['App']['ConvertRate'](arg1);
}

export function Convexity(arg1, arg2) {
  return window['go']['main']['App']['Convexity'](arg1, arg2);
}

export function EffectiveToNominal(arg1, arg2) {
  return window['go']['main']['App']['EffectiveToNominal'](arg1, arg2);
}

export function ForceOfInterest(arg1) {
  return window['go']['main']['App']['ForceOfInterest'](arg1);
}

export function GetCSVHeaders(arg1) {
  return window['go']['main']['App']['GetCSVHeaders'](arg1);
}

export function GetTableData(arg1) {
  return window['go']['main']['App']['GetTableData'](arg1);
}

export function GetTableNames() {
  return window['go']['main']['App']['GetTableNames']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InterestFromForce(arg1) {
  return window['go']['main']['App']['InterestFromForce'](arg1);
}

export function LoadTableFromData(arg1, arg2) {
  return window['go']['main']['App']['LoadTableFromData'](arg1, arg2);
}

export function LoadTableFromFile(arg1, arg2) {
  return window['go']['main']['App']['LoadTableFromFile'](arg1, arg2);
}

export function MacaulayDuration(arg1, arg2) {
  return window['go']['main']['App']['MacaulayDuration'](arg1, arg2);
}

export function ModifiedDuration(arg1, arg2) {
  return window['go']['main']['App']['ModifiedDuration'](arg1, arg2);
}

export function NominalToEffective(arg1, arg2) {
  return window['go']['main']['App']['NominalToEffective'](arg1, arg2);
}

export function ProcessCensus(arg1) {
  return window['go']['main']['App']['ProcessCensus'](arg1);
}

export function ProcessCensusFromData(arg1, arg2) {
  return window['go']['main']['App']['ProcessCensusFromData'](arg1, arg2);
}

export function ProcessCensusParallel(arg1) {
  return window['go']['main']['App']['ProcessCensusParallel'](arg1);
}

export function ProcessPV(arg1) {
  return window['go']['main']['App']['ProcessPV'](arg1);
}

export function QueryEx(arg1, arg2) {
  return window['go']['main']['App']['QueryEx'](arg1, arg2);
}

export function QueryPx(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryPx'](arg1, arg2, arg3);
}

export function QueryQx(arg1, arg2) {
  return window['go']['main']['App']['QueryQx'](arg1, arg2);
}

export function RunGBM(arg1) {
  return window['go']['main']['App']['RunGBM'](arg1);
}

export function RunProfitTest(arg1) {
  return window['go']['main']['App']['RunProfitTest'](arg1);
}

export function RunVasicek(arg1) {
  return window['go']['main']['App']['RunVasicek'](arg1);
}

export function V(arg1) {
  return window['go']['main']['App']['V'](arg1);
}

export function VStar(arg1, arg2) {
  return window['go']['main']['App']['VStar'](arg1, arg2);
}

export function VaR(arg1, arg2) {
  return window['go']['main']['App']['VaR'](arg1, arg2);
}
