// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnnuityCertainDue(arg1:number,arg2:number):Promise<number>;

export function AnnuityCertainImmediate(arg1:number,arg2:number):Promise<number>;

export function CTE(arg1:Array<number>,arg2:number):Promise<number>;

export function CalcAnnuity(arg1:models.AnnuityRequest):Promise<models.AnnuityResponse>;

export function CalcReserve(arg1:models.ReserveRequest):Promise<models.ReserveResponse>;

export function CalculatePV(arg1:number,arg2:number,arg3:number):Promise<number>;

export function CalculatePVStar(arg1:number,arg2:number,arg3:number,arg4:number):Promise<number>;

export function ComputeRiskMetrics(arg1:Array<number>):Promise<models.RiskResponse>;

export function ConvertRate(arg1:models.RateConvertRequest):Promise<models.RateConvertResponse>;

export function Convexity(arg1:number,arg2:Array<number>):Promise<number>;

export function EffectiveToNominal(arg1:number,arg2:number):Promise<number>;

export function ForceOfInterest(arg1:number):Promise<number>;

export function GetCSVHeaders(arg1:string):Promise<Array<string>>;

export function GetTableData(arg1:models.TableDataRequest):Promise<models.TableDataResponse>;

export function GetTableNames():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InterestFromForce(arg1:number):Promise<number>;

export function LoadTableFromFile(arg1:string,arg2:string):Promise<void>;

export function MacaulayDuration(arg1:number,arg2:Array<number>):Promise<number>;

export function ModifiedDuration(arg1:number,arg2:Array<number>):Promise<number>;

export function NominalToEffective(arg1:number,arg2:number):Promise<number>;

export function ProcessCensus(arg1:models.CensusRequest):Promise<models.CensusResponse>;

export function ProcessCensusParallel(arg1:models.CensusRequest):Promise<models.CensusResponse>;

export function ProcessPV(arg1:models.PVRequest):Promise<models.PVResponse>;

export function QueryEx(arg1:string,arg2:number):Promise<number>;

export function QueryPx(arg1:string,arg2:number,arg3:number):Promise<number>;

export function QueryQx(arg1:string,arg2:number):Promise<number>;

export function RunGBM(arg1:models.MonteCarloRequest):Promise<models.MonteCarloResponse>;

export function RunVasicek(arg1:models.MonteCarloRequest):Promise<models.MonteCarloResponse>;

export function V(arg1:number):Promise<number>;

export function VStar(arg1:number,arg2:number):Promise<number>;

export function VaR(arg1:Array<number>,arg2:number):Promise<number>;
